### PR TITLE
Removed duplicate OUTOFSTOCK key in language files

### PR DESCRIPTION
**Pull request by EdgarMendoza**

### CODE REVIEW

**Comment by softyoda** [comment]
Does SEO addon still in activity ? When i add it i have an error :

`"Failed to read en.yaml: Duplicate key "OUTOFSTOCK" detected at line 57 (near "OUTOFSTOCK: "Out of Stock"")."`
on every pages of my site and admin pannel.



https://discourse.getgrav.org/t/grav-1-7-yamllinter-does-not-detect-failing-translation-files/16527

Is that normal ?

**Review by aloxe — APPROVED** [review]

**Review by LuanHimmlisch — APPROVED** [review]

**Comment by paulmassen** [comment]
Sorry. I had no time to update the plugin...

I will try to take a look and make it compatible with Grav and Admin's latest version, but meanwhile I would recommend not using it...

**Comment by LuanHimmlisch** [comment]
@paulmassen the plugin works as a charm, it's by far the best SEO plugin, thanks a lot. This was the only error to my knowledge

**Comment by aloxe** [comment]
@paulmassen I second that. installed it on latest grav with a few different themes and I had no problem but the one fixed by this PR.

**Comment by nnhthuan** [comment]
Do not remove OUTOFSTOCK, just change it to OUT_OF_STOCK, then change the references in blueprints/seo.yaml

**Comment by aloxe** [comment]
@nnhthuan While the change you suggest fixes the bug it leaves an unused string for translators to maintain. Removing the duplicate is far simplier.

**Pull request merged**
