### PR TITLE
upload file

### PR DESCRIPTION
**Pull request by JohnMica**
added upload file for simpler user usage

### CODE REVIEW

**Comment by JohnMica** [comment]
still new to github so it seems that both syncs have made it to the pull request.
hope this is ok with you.

ON another note, when trying to change the filepicker to file for facebook tehre is an error about array conversion to string --- not sure why so i left the facebook to filepicker. hopefully you can take a look at that as well. it would be nice to be able to upload/select different photos for twitter and facebook if possible.

**Comment by paulmassen** [comment]
Thanks for this PR. I thought about that too, but I think it might make more sense for users to pick an image which is displayed in the page instead of uploading another one.

Let's see what other users think and we will make the change accordingly.
Also, there is a new Grav Mediapicker feature, on the next update that might be a good fit, let's see.
If for now you want to use it with file fields, you will have to adjust the twig template seo_data.html.twig accordingly.

Accessing an image uploaded in a file field is made with something like:
{% for uploadedimages in myfilefield %}
{# uploadedimages is an array with all the images #}
{{ uploadedimages|first.url }}
{# this above get the first image is in the array and display its url #}
{% endfor %}

If you still have trouble, do not hesitate to branch and I will PR on your branch if needed.

**Comment by JohnMica** [comment]
Paul, the idea was that at times certain pages have a header image stored somewhere else (such as theme://images/bla.jpg ) and thus not accessible with page.media in the twig since there is no media on the page.
Or using a system such as Cloudinary which has some interesting options for dynamic images - images show on the page but not from page folder.
I've modified it to upload to give the option to choose, when using images from somewhere else.

**Comment by paulmassen** [comment]
I see, but removing the filepicker means user won't be able to pick an image already uploaded, and will have to manually upload it again.

Our best choices will be to upgrade to the mediapicker field, which will be present in next Grav release and which will allow user to pick an image, no matter its location in the site.

I'm still open to reconsider it if a majority think it is a better choice for this plugin.

Thanks again

Paul

**Pull request closed without merging**
